- hosts: localhost
  vars_files:
    - vars.yml
  vars_prompt:
    - name: syncthing_password
      prompt: "What is your syncthing password?"
  tasks:
  - include: tasks/facts.yml
  - include: tasks/dirs.yml
  - include: tasks/work.yml
  - include: tasks/crypt.yml
