---
  - name: Change ssh dir permission
    file:
      state: directory
      path: "{{ ssh_path }}"
      mode: 0700
  - name: Change shared permission
    file:
      path: "{{ ssh_path }}/{{ item }}"
      mode: 0644
    with_items:
      - authorized_keys
      - id_rsa.pub
      - known_hosts
  - name: Change private key permission
    file:
      path: "{{ ssh_path }}/id_rsa"
      mode: 0600
  - name: Change gnupg dir permission
    file:
      state: directory
      path: "{{ home_path }}/.gnupg"
      mode: 0700
