---
  - name: Create extra home dirs
    file:
      state: directory
      path: "{{ item }}"
    with_items:
      - "{{ apps_path }}"
      - "{{ browser_path }}"
      - "{{ torrent_path }}"
  - name: Link dirs
    file:
      state: link
      force: yes
      src: "{{ sync_path }}/{{ item }}"
      dest: "{{ home_path }}/{{ item }}"
    with_items: "{{ link_dirs }}"
  - name: Link dotfiles
    file:
      state: link
      force: yes
      src: "{{ item }}"
      dest: "{{ home_path }}/.{{ item | basename }}"
    with_lines:
      - "find {{ settings_dot_path }} -mindepth 1 -maxdepth 1"
  - name: Link config 
    file:
      state: link
      force: yes
      src: "{{ item }}"
      dest: "{{ config_path }}/{{ item | basename }}"
    with_lines:
      - "find {{ settings_config_path }} -mindepth 1 -maxdepth 1"
  - name: Link local bin
    file:
      state: link
      force: yes
      src: "{{ settings_local_bin_path }}"
      dest: "{{ local_bin_path }}"
  - name: Make local bin executable
    file:
      dest: "{{ item }}"
      mode: a+x
    with_fileglob: "{{ settings_local_bin_path }}/*"
