---
  - name: Get home
    shell: echo ~
    register: home_cmd
    changed_when: false
  - name: Get user
    shell: whoami
    register: user_cmd
    changed_when: false
  - name: Set user
    set_fact:
      user: "{{ user_cmd.stdout }}"
  - name: Set home path
    set_fact:
      home_path: "{{ home_cmd.stdout }}"
  - name: Set sync path
    set_fact:
      sync_path: "{{ home_path }}/{{ sync_dir }}"
  - name: Set home paths
    set_fact:
      work_path: "{{ home_path }}/{{ work_dir }}"
      wiki_path: "{{ home_path }}/{{ documents_dir }}/{{ wiki_dir }}"
      downloads_path: "{{ home_path }}/{{ downloads_dir }}"
      apps_path: "{{ home_path }}/{{ apps_dir }}"
      proj_path: "{{ sync_path }}/{{ proj_dir }}"
      wallpapers_path: "{{ home_path }}/{{ pictures_dir }}/{{ wallpapers_dir }}"
      screenshots_path: "{{ home_path }}/{{ pictures_dir }}/{{ screenshots_dir }}"
  - name: Set os paths
    set_fact:
      config_path: "{{ home_path }}/.config"
      ssh_path: "{{ home_path }}/.ssh"
      gnupg_path: "{{ home_path }}/.gnupg"
      local_bin_path: "{{ home_path }}/.local/bin"
      ext_path: "{{ home_path }}/.local/share/gnome-shell/extensions"
      evo_mail_path: "{{ home_path }}/.local/share/evolution/mail/local"
      accountsservice_user_path: "/var/lib/AccountsService/users/{{ user }}"
  - name: Set sync paths
    set_fact:
      mail_path: "{{ sync_path }}/{{ mail_dir }}"
      settings_path: "{{ sync_path }}/{{ settings_dir }}"
  - name: Set downloads paths
    set_fact:
      browser_path: "{{ downloads_path }}/{{ browser_dir }}"
      torrent_path: "{{ downloads_path }}/{{ torrent_dir }}"
  - name: Set settings paths
    set_fact:
      settings_dot_path: "{{ settings_path }}/{{ settings_dot_dir }}"
      settings_config_path: "{{ settings_path }}/{{ settings_config_dir }}"
      settings_local_bin_path: "{{ settings_path }}/{{ settings_local_bin_dir }}"
  - name: Set workspace paths
    set_fact:
      work_git_path: "{{ work_path }}/{{ work_git_dir }}"
      work_tmp_path: "{{ work_path }}/{{ work_tmp_dir }}"
      work_rpm_path: "{{ work_path }}/{{ work_rpm_dir }}"
      work_flatpak_path: "{{ work_path }}/{{ work_flatpak_dir }}"
      work_proj_path: "{{ work_path }}/{{ work_proj_dir }}"
      work_wiki_path: "{{ work_path }}/{{ work_wiki_dir }}"
  - name: Set dynamic gsettings    
    set_fact:
      dynamic_gsettings:
      - schema: org.gnome.desktop.background
        key: picture-uri 
        value: "'{{ wallpapers_path }}/{{ background }}'"
      - schema: org.gnome.desktop.screensaver
        key: picture-uri 
        value: "'{{ wallpapers_path }}/{{ screensaver }}'"
      - schema: org.gnome.gnome-screenshot
        key: auto-save-directory
        value: "'{{ screenshots_path }}'"
