---
  - name: Install gui packages
    become: true
    package: 
      state: present
      name:
      - syncthing
      - keepassxc
      - pop-icon-theme
      - hunspell-da
      - hyphen-da
      - mythes-da
      - autocorr-da
      - libreoffice-langpack-da
  - name: Remove gui packages
    become: true
    package:
      state: absent
      name:
      - gnome-shell-extension-*
  - name: Increase max user watches
    become: true
    lineinfile:
      path: "{{ accountsservice_user_path }}"
      regexp: "^fs.inotify.max_user_watches="
      line: "fs.inotify.max_user_watches=524288"
  - name: Set user picture
    become: true
    lineinfile:
      path: "{{ accountsservice_user_path }}"
      regexp: "^Icon="
      line: "Icon={{ home_path }}/{{ pictures_dir }}/{{ profile_dir}}/{{ profile }}"
  - name: Link evolution mail
    file:
      state: link
      src: "{{ mail_path }}"
      dest: "{{ evo_mail_path }}"
