---
  - name: Create work dirs
    file:
      state: directory
      path: "{{ item }}"
    with_items:
      - "{{ work_git_path }}"
      - "{{ work_tmp_path }}"
      - "{{ work_rpm_path }}"
      - "{{ work_flatpak_path }}"
  - name: Link project dir
    file:
      state: link
      src: "{{ proj_path }}"
      dest: "{{ work_proj_path }}"
  - name: Link wiki dir
    file:
      state: link
      src: "{{ wiki_path }}"
      dest: "{{ work_wiki_path }}"
